In [1]:
import numpy as np
from data import X,Y
import copy
import sklearn
import sklearn.datasets
import sklearn.linear_model
#from planar_utils import plot_decision_boundary, sigmoid, load_planar_dataset, load_extra_datasets
import matplotlib.pyplot as plt
import math



In [72]:
X

array([[ 1.20444229e+00,  1.58709904e-01,  9.52471960e-02,
         3.49178475e-01,  6.94150378e-01,  1.62065038e+00,
         1.53856225e+00,  3.63085641e-02,  4.74591109e-01,
         1.65695828e-01,  1.66446249e+00,  8.40285720e-01,
         2.61695163e-01,  2.31614896e-01,  1.58013020e+00,
         6.35509950e-03,  6.80610419e-01,  1.21400432e-01,
         1.13281261e+00,  1.61505892e+00,  1.66454441e-01,
         1.72438241e+00,  1.88667246e+00,  1.72327227e+00,
         1.54661332e+00,  9.84590400e-01,  1.45313345e+00,
         7.49043388e-01,  1.45048341e+00,  1.64287865e+00,
         1.28141487e+00,  1.59574104e+00,  1.46298294e+00,
         1.46629048e+00,  1.54348961e+00,  1.57013416e+00,
         1.22995404e+00,  1.31142345e+00, -1.99364553e+00,
         3.94564752e-01,  1.51715449e+00,  1.69169139e+00,
         1.74186686e+00, -2.91373382e+00,  7.52150898e-01,
         1.68537303e+00,  3.71160238e-01, -3.73033884e+00,
         3.52484080e-01, -1.48694206e+00, -7.45290416e-0

In [13]:
def layer_sizes(X,Y):
    n_x = X.shape[0]
    n_h = 4
    n_y = Y.shape[0]
    return(n_x,n_h,n_y)

In [14]:
n_x,n_h,n_y = layer_sizes(X,Y)

In [24]:
def initialize_params(n_x,n_h,n_y):
    W1 = np.random.randn(n_h,n_x) *0.01
    b1 = np.zeros((n_h,1))
    W2 = np.random.randn(n_y,n_h)*0.01
    b2 = np.zeros((n_y,1))

    parameters = { "W1": W1,
                   "W2": W2,
                   "b1":b1,
                   "b2":b2
                 }

    return parameters

In [27]:
parameters = initialize_params(n_x, n_h, n_y)

print("W1 = " + str(parameters["W1"]))
print("b1 = " + str(parameters["b1"]))
print("W2 = " + str(parameters["W2"]))
print("b2 = " + str(parameters["b2"]))

W1 = [[ 0.00380472 -0.00217135]
 [ 0.01173531 -0.02343603]
 [ 0.01161521  0.00386078]
 [-0.01133133  0.00433093]]
b1 = [[0.]
 [0.]
 [0.]
 [0.]]
W2 = [[-0.00304086  0.02585295  0.01835333  0.0044069 ]]
b2 = [[0.]]


In [17]:
parameters["b2"].shape

(1, 1)

In [28]:
def sigmoid(x):
    z = 1/(1+np.exp(-x))
    return z

In [29]:
def tanh(x):
    z = (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))
    return z, x

In [30]:
# GRADED FUNCTION:forward_propagation

def forward_propagation(X, parameters):
    
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]
    
    
  
    Z1 = np.dot(W1,X) + b1
    A1 = np.tanh(Z1)
    Z2 = np.dot(W2,A1) +b2
    A2 = sigmoid(Z2)
    
    assert(A2.shape == (1, X.shape[1]))
    
    cache = {"Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2}
    
    return A2, cache

In [63]:
A2, cache = forward_prop(X, parameters)

In [ ]:

def compute_cost(A2, Y):
    m = Y.shape[1]

    # Compute the cross-entropy loss
    logprobs = np.dot(np.log(A2), Y.T) + np.dot(np.log(1 - A2), (1 - Y).T)
    cost = -np.sum(logprobs) / m

    # Ensure cost is a scalar (convert to float and squeeze)
    cost = float(np.squeeze(cost))

    return cost


In [ ]:
cost = compute_cost(A2, Y)

In [ ]:
def back_prop(parameters,Y,X,cache):

    m = Y.shape[1]

    W1 = parameters["W1"]
    W2 = parameters["W2"]

    A1 = cache["A1"]
    A2 = cache["A2"]

    dZ2 = A2 - Y
    dW2 = np.dot(dZ2,A1.T)/m
    db2 = (np.sum(dZ2,axis=1,keepdims=True))/m
    dZ1 = np.dot(W2.T,dZ2)*(1 - np.power(A1, 2))
    dW1 = np.dot(dZ1,X.T)
    db1 = (np.sum(dZ1,axis=1,keepdims=True))/m

    grads = {"dW1": dW1,
             "db1": db1,
             "dW2": dW2,
             "db2": db2}
    
    return grads


    

In [ ]:
t_X = np.array([[ 1.62434536, -0.61175641, -0.52817175],
        [-1.07296862,  0.86540763, -2.3015387 ]])
t_Y = np.array([[ True, False,  True]])

In [ ]:
grads = back_prop(parameters,Y,X,cache)

In [ ]:
# GRADED FUNCTION: update_parameters

def update_parameters(parameters, grads, learning_rate = 1.2):
    
   
    W1 = copy.deepcopy(parameters["W1"])
    b1 = parameters["b1"]
    W2 = copy.deepcopy(parameters["W2"])
    b2 = parameters["b2"]
    
    dW1 = grads["dW1"]
    db1 = grads["db1"]
    dW2 = grads["dW2"]
    db2 = grads["db2"]
  
    W1 = W1 - learning_rate*dW1
    b1 = b1 - learning_rate*db1
    W2 = W2 - learning_rate*dW2
    b2 = b2 - learning_rate*db2
    
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [82]:
class NN_model:
    def __init__(self):
        self.parameters = {}

    def layer_sizes(self,X,Y):
        n_x = X.shape[0]
        n_h = 4
        n_y = Y.shape[0]
        return(n_x,n_h,n_y)
    
    def sigmoid(self,x):
        z = 1/(1+np.exp(-x))
        return z

    def initialize_params(self,n_x,n_h,n_y):
        np.random.seed(2)
        W1 = np.random.randn(n_h,n_x) *0.01
        b1 = np.zeros((n_h,1))
        W2 = np.random.randn(n_y,n_h) *0.01
        b2 = np.zeros((n_y,1))

        parameters = { "W1": W1,
                    "W2": W2,
                    "b1":b1,
                    "b2":b2
                    }

        return parameters
    
    def forward_prop(self,X,parameters):

        W1 = parameters["W1"]
        W2 = parameters["W2"]
        b1 = parameters["b1"]
        b2 = parameters["b2"]

        Z1 = np.dot(W1,X) + b1
        A1 = np.tanh(Z1)
        Z2 = np.dot(W2,A1) + b2
        A2 = self.sigmoid(Z2)

        assert(A2.shape == (1, X.shape[1]))

        cache = { "Z1": Z1,
                    "Z2": Z2,
                    "A1":A1,
                    "A2":A2
                    }
        
        return A2,cache
    
    
    def compute_cost(self,A2, Y):
        m = Y.shape[1]

        # Compute the cross-entropy loss
        logprobs = np.multiply(np.log(A2),Y) + np.multiply(np.log(1-A2),(1-Y))
        cost = -np.sum(logprobs)/m

        # Ensure cost is a scalar (convert to float and squeeze)
        cost = float(np.squeeze(cost))

        return cost
    
    def back_prop(self,parameters,Y,X,cache):

        m = Y.shape[1]

        W1 = parameters["W1"]
        W2 = parameters["W2"]

        A1 = cache["A1"]
        A2 = cache["A2"]

        dZ2 = A2 - Y
        dW2 = np.dot(dZ2,A1.T)/m
        db2 = (np.sum(dZ2,axis=1,keepdims=True))/m
        dZ1 = np.dot(W2.T,dZ2)*(1 - np.power(A1, 2))
        dW1 = np.dot(dZ1,X.T)/m
        db1 = (np.sum(dZ1,axis=1,keepdims=True))/m

        grads = {"dW1": dW1,
                "db1": db1,
                "dW2": dW2,
                "db2": db2}
        
        return grads
    
    def update_parameters(self,parameters, grads, learning_rate = 1.2):
    
   
        W1 = copy.deepcopy(parameters["W1"])
        b1 = parameters["b1"]
        W2 = copy.deepcopy(parameters["W2"])
        b2 = parameters["b2"]
        
        dW1 = grads["dW1"]
        db1 = grads["db1"]
        dW2 = grads["dW2"]
        db2 = grads["db2"]
    
        W1 = W1 - learning_rate*dW1
        b1 = b1 - learning_rate*db1
        W2 = W2 - learning_rate*dW2
        b2 = b2 - learning_rate*db2
        
        
        parameters = {"W1": W1,
                    "b1": b1,
                    "W2": W2,
                    "b2": b2}
        
        return parameters


    

    
    def fit(self, X, Y, n_h, epochs):
        n_x = self.layer_sizes(X, Y)[0]
        n_y = self.layer_sizes(X, Y)[2]

        self.parameters = self.initialize_params(n_x, n_h, n_y)

        for i in range(epochs):
            A2, cache = self.forward_prop(X, self.parameters)
            cost = self.compute_cost(A2, Y)
            grads = self.back_prop(self.parameters, Y, X, cache)
            self.parameters = self.update_parameters(self.parameters, grads)

            if i % 10000 == 0:
                print (f"The cost after {i} iterations is : {cost}")

        return self.parameters
    
    def predict(self,X):
        if not self.parameters:
            raise ValueError("Model parameters are not initialized. Please call fit() first.")
        
        A2 , cache = self.forward_prop(X,self.parameters)
        predictions = (A2 > 0.5)

        return predictions
        


    

In [83]:
model = NN_model()

In [84]:
model.fit(X,Y,n_h=4,epochs=100000)

The cost after 0 iterations is : 0.6930480201239767
The cost after 10000 iterations is : 0.21782326452623757
The cost after 20000 iterations is : 0.21394864509151532
The cost after 30000 iterations is : 0.21223596441015277
The cost after 40000 iterations is : 0.21116955098214155
The cost after 50000 iterations is : 0.21039722279467102
The cost after 60000 iterations is : 0.20978631016341356
The cost after 70000 iterations is : 0.20927461523303775
The cost after 80000 iterations is : 0.2088290493390429
The cost after 90000 iterations is : 0.20843039557770815


{'W1': array([[  0.11606379, -11.90731167],
        [-22.5682537 ,   6.23335304],
        [-29.0578526 , -32.44307817],
        [ 15.16013709, -16.05029459]]),
 'b1': array([[ 0.03761145],
        [-0.8916181 ],
        [-0.0163095 ],
        [ 0.0273445 ]]),
 'W2': array([[-14.26551518,   3.9096836 ,   7.4122188 ,  11.99323986]]),
 'b2': array([[-0.06794237]])}

In [85]:
# Print accuracy
predictions = model.predict(X)
accuracy = float((np.dot(Y, predictions.T).item() + np.dot(1 - Y, 1 - predictions.T).item()) / float(Y.size) * 100)
print(f'Accuracy: {accuracy:.2f}%')

Accuracy: 91.00%


In [40]:
params = model.initialize_params(2,4,1)
params

{'W1': array([[-0.00416758, -0.00056267],
        [-0.02136196,  0.01640271],
        [-0.01793436, -0.00841747],
        [ 0.00502881, -0.01245288]]),
 'W2': array([[-0.01057952, -0.00909008,  0.00551454,  0.02292208]]),
 'b1': array([[0.],
        [0.],
        [0.],
        [0.]]),
 'b2': array([[0.]])}

In [41]:
X

array([[ 1.20444229e+00,  1.58709904e-01,  9.52471960e-02,
         3.49178475e-01,  6.94150378e-01,  1.62065038e+00,
         1.53856225e+00,  3.63085641e-02,  4.74591109e-01,
         1.65695828e-01,  1.66446249e+00,  8.40285720e-01,
         2.61695163e-01,  2.31614896e-01,  1.58013020e+00,
         6.35509950e-03,  6.80610419e-01,  1.21400432e-01,
         1.13281261e+00,  1.61505892e+00,  1.66454441e-01,
         1.72438241e+00,  1.88667246e+00,  1.72327227e+00,
         1.54661332e+00,  9.84590400e-01,  1.45313345e+00,
         7.49043388e-01,  1.45048341e+00,  1.64287865e+00,
         1.28141487e+00,  1.59574104e+00,  1.46298294e+00,
         1.46629048e+00,  1.54348961e+00,  1.57013416e+00,
         1.22995404e+00,  1.31142345e+00, -1.99364553e+00,
         3.94564752e-01,  1.51715449e+00,  1.69169139e+00,
         1.74186686e+00, -2.91373382e+00,  7.52150898e-01,
         1.68537303e+00,  3.71160238e-01, -3.73033884e+00,
         3.52484080e-01, -1.48694206e+00, -7.45290416e-0

In [63]:
A2, cache = model.forward_prop(X,params)
A2, cache

(array([[0.49758522, 0.50118408, 0.50101626, 0.50166816, 0.49798755,
         0.50342952, 0.49791147, 0.50067931, 0.49824845, 0.49868326,
         0.49778158, 0.50281363, 0.49848205, 0.49869618, 0.49787555,
         0.49970507, 0.49782831, 0.49903748, 0.49741077, 0.49760617,
         0.49870998, 0.49831659, 0.49798034, 0.49778287, 0.49848443,
         0.49738752, 0.49761861, 0.49783152, 0.49764125, 0.49840811,
         0.49749702, 0.49757631, 0.49744749, 0.49729777, 0.49759634,
         0.49841679, 0.4976734 , 0.49894372, 0.50070457, 0.49979546,
         0.49864018, 0.49785033, 0.49804909, 0.50074256, 0.49951341,
         0.49844281, 0.49980859, 0.50041964, 0.49982887, 0.5005966 ,
         0.50035644, 0.49966975, 0.49885761, 0.49971592, 0.5001081 ,
         0.50073001, 0.50058296, 0.50058705, 0.50065019, 0.50057573,
         0.50004022, 0.50027068, 0.50058953, 0.50063417, 0.50055707,
         0.50063419, 0.50007888, 0.49984634, 0.49984418, 0.50017515,
         0.50009548, 0.50061945, 0

In [64]:
cost = model.compute_cost(A2,Y)
cost

0.6925360700692968

In [65]:
grads = model.back_prop(params,Y,X,cache)
grads

{'dW1': array([[ 0.00030763, -0.00272476],
        [ 0.00071896, -0.00588539],
        [-0.00028827,  0.00265646],
        [-0.00097823,  0.00819196]]),
 'db1': array([[ 3.01764391e-07],
        [-6.23724953e-06],
        [-7.71127013e-07],
        [ 5.44216301e-06]]),
 'dW2': array([[ 0.0020369 ,  0.00661727, -0.00273807, -0.00772135]]),
 'db2': array([[-4.023238e-05]])}

In [66]:
params = model.update_parameters(params,grads)
params

{'W1': array([[-0.00572266,  0.01317632],
        [-0.02403315,  0.03868749],
        [-0.01675045, -0.01921578],
        [ 0.00931173, -0.04909946]]),
 'b1': array([[-1.03415314e-06],
        [ 1.83856793e-05],
        [ 2.01174810e-06],
        [-1.30850292e-05]]),
 'W2': array([[-0.01651713, -0.03877201,  0.01702488,  0.05276214]]),
 'b2': array([[0.00013556]])}